# Generated by Django 4.1.1 on 2022-09-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.PositiveBigIntegerField(blank=True, null=True)),
                ('grade_10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree', models.CharField(choices=[('High School', 'High School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], default='High School', max_length=32)),
                ('experience', models.IntegerField()),
                ('field_of_study', models.CharField(max_length=256)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.applicant')),
            ],
        ),
    ]
