# Generated by Django 4.1.1 on 2022-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_applicant_age_applicant_gender_applicant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
