# Generated by Django 4.1.1 on 2022-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_applicant_id_applicant_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
