# Generated by Django 4.1.1 on 2022-09-22 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Incomplete', max_length=32),
        ),
        migrations.AddField(
            model_name='applicant',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
