# Generated by Django 4.1.1 on 2022-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_applicant_status_applicant_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
