# Generated by Django 4.1.1 on 2022-09-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_applicant_id_alter_applicant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='grade_10',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='grade_12',
        ),
    ]
