# Generated by Django 4.1.1 on 2022-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_job_company_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
