# Generated by Django 4.1.1 on 2022-09-28 12:05

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_applicant_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.upload_to),
        ),
    ]
