# Generated by Django 4.1.1 on 2022-09-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_job_remote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created']},
        ),
    ]
